### ISSUE TITLE
Add a striplog to a well

### ISSUE THREAD

**Issue by kwinkunks** [agile-geoscience/welly#10]
Perhaps `striplog` is just another constituent... could be weird attaching picks that way. Might need to rename striplog  : P

Alt: could subclass it

**Comment by EvanBianco** [comment]
In addition to being able to add striplogs to a well. We also need to be able to add a _curve_ to a well (that has already been instantiated).

Say I instantiate a well from a LASfile using `welly.from_las(LASfile)`, and then I want to be able to add a striplog (as a striplog object) or striplog-lithology converted to array as digits.

Adding a curve to an existing set of curves, might be easier than adding a striplog?

**Comment by kwinkunks** [comment]
Adding a striplog is easy now that we just have a big bag called `well.data`...

    w['lithology'] = Striplog.from_image('my_file.png', start=0, stop=1000, legend=legend)

And you can add a curve with

    w.add_curves_from_las('myfile.las')

...added in d4a1ed2
