### ISSUE TITLE
Add wells to project or load from list

### ISSUE THREAD

**Issue by ryscar13** [agile-geoscience/welly#106]
I have a list of paths to wells and am hoping to load them to a project class. It would be great to be able to load all of these to a project using the list or two iterate through the list and add each well to a project class. 

Is this already possible?

**Comment by EvanBianco** [comment]
@ryscar13,

Yes, this is possible. If you have the list of paths in a list, then you can create a list of `Well` objects:

`from welly import Project, Well`

`list_of_wells = [Well.from_las(file) for file in well_paths]`

and then pass this list to the `Project` class.

`my_proj = Project(wells)`

then you can view a nice rendering of these wells in an HTML table in the Jupyter Notebook using, 

`from IPython.display import HTML`

`HTML(p.curve_table_html())`

**Comment by kwinkunks** [comment]
Note that if you can express the filenames with a glob pattern (e.g. `../data/wells/well_*/*.[LlAaSs]` then you can also pass that directly to the `Project.from_las()` constructor, e.g. 

    p = Project.from_las("../data/wells/well_*/*.[LlAaSs]")

**Comment by ryscar13** [comment]
Ahhhh I see. Was unable to make the call with a glob pattern and was instead trying to pass a list of paths directly into the Projects function. I'll try this next week.

Thank you both!
