### ISSUE TITLE
striplog to curve

### ISSUE THREAD

**Issue by kwinkunks** [agile-geoscience/welly#11]
`striplog` does this, just need to make sure it 'just works' when attached to `welly`... eg we should be able to use the depth basis automagically.

**Comment by EvanBianco** [comment]
I was able to do this by passing in the `start`, `step`, `mnemonic`, `units`, etc., as params to the `Curve` object along with a 1-D array created from `striplog.to_log()`

![image](https://cloud.githubusercontent.com/assets/1699959/13465972/5d460f12-e06e-11e5-9f3a-2ffa737a3388.png)

**Comment by kwinkunks** [comment]
I think the current workflow is OK, at least until welly and striplog are merged, if ever.
