### ISSUE TITLE
Allow use of `alias` in making DataFrame

### ISSUE THREAD

**Issue by kwinkunks** [agile-geoscience/welly#122]
Should be able to pass `alias` to `w.df()`, and control what the resulting column is called (i.e. called after the alias key, e.g. `Gamma`, or after the curve mnemonic, e.g. `GR`).

**Comment by ThomasMGeo** [comment]
As long as it's an option, I think that would be great. Right now I am working with wells that have AT90 in the upper section and ILD logs in the reservoir section. Would it merge these two into one RESD curve?

**Comment by kwinkunks** [comment]
No, it wouldn't do that... `alias` just chooses the one with the highest priority.

Merging would be cool though!
