### ISSUE TITLE
TypeError 0 is not a string (plotting well imported from welly-generated LAS)

### ISSUE THREAD

**Issue by awgeo** [agile-geoscience/welly#126]
**Problem:** 
When trying to plot a well, imported from a Welly-generated .LAS file, I get "TypeError 0 is not a string" which is raised against "axes[0].set_ylim([lower, upper])".

Follow the steps below to import > export > import the LAS file.
LAS file (from the Volve data set) and full error message attached.

[Welly bug report.zip](https://github.com/agile-geoscience/welly/files/4491935/Welly.bug.report.zip)

**To reproduce:**
w = Well.from_las('STAT1990__30-1__15-9-19_SR__COMPOSITE__1.LAS')
w.plot()
w.to_las('out.las')
z = Well.from_las('out.las')
z.plot()

**Expected:** 
Welly can plot the original LAS file, so should be expected to plot after running .to_las() then .from_las().

**Comment by dcslagel** [comment]
Triage findings so far:

1. The welly/well.py code related to setting lower and upper hasn't changed recently.
2. The same issue can be seen using the standard las file tutorial/P-129_out.las. 
3. In the error case the type of lower is <class 'str'> with value 'None'
   Side-note: if both variables are changed to be either both strings or both numbers then a
    plot will be drawn.
4. In looking at tutorial/P-129_out.las with w.plot(), the lower is a <class 'numpy.float64> with
    value 1939.1376000000012.  So it is not a <class 'str'> as seen in the error case.
5. 1939.1376 is in tutorial/P-129_out.las as:
    STOP .M      1939.13760      :STOP DEPTH     
    and as the last DEPT element in the data section as:
    1939.1376000
6. 1939.1376 is in the out.las as
    STOP.m         1939.1376000000012 : STOP DEPTH
    and as the last DEPT element in the data section as:
    1939.13760

So it seems like the out.las has different values for STOP DEPT than the original file. Maybe the STOP value is not found because it is more precise than the DEPT value and so get set to 'None'

DC

**Comment by dcslagel** [comment]
### work around

Using the built-in `funcs` parameter we can work around this issue.
The following code will run without the type error.

```python
w = Well.from_las('STAT1990__30-1__15-9-19_SR__COMPOSITE__1.LAS')
w.plot()
w.to_las('out.las')

# Add transform function(s) -----------------
def str_none_to_none(value):
    if value == 'None':
        return None

transform_functions = {
    'TD': str_none_to_none,
}
# z = Well.from_las('out.las')
z = Well.from_las('myout.las', funcs=transform_functions)
# -------------------------------------------
z.plot()

**Comment by kinverarity1** [comment]
Would the underlying problem here be that lasio/welly is writing the python object None to `out.las` as the string `'None'`? I haven't tested this, just genuinely curious. If so we should fix that.

**Comment by dcslagel** [comment]
Thats a good point!  

I'll look at that today.  Step one it to see whether the internal value is the same between Lasio and Welly just before writing.  Also it will be useful to see if there is a difference between Lasio and Welly about what gets written.  If it is a fundamental read/write issue, then design-wise it would be nice to handle it in Lasio. 

There is also a question of whether this should be kept specific to the 'TD' mnemonic, or be configurable for a set of mnemonics, or be handled in a general way.

It does feel like Lasio and Welly should each have a match of their original las object data after a cycle of read(las), write(new.las), read(new.las).

**Comment by dcslagel** [comment]
Yes,  Lasio is writing the python None object to the string 'None' when writing to a file.   Not yet sure how it should be handed....

**Comment by dcslagel** [comment]
Related Lasio Issue:   
https://github.com/kinverarity1/lasio/issues/377

**Comment by kwinkunks** [comment]
I believe this is fixed in `lasio` now, so I'm closing it here. Thanks DC and Alan! (And Kent of course!)
