### ISSUE TITLE
Well.from_las fails when using pathlib.Path object(s)

### ISSUE THREAD

**Issue by kinverarity1** [agile-geoscience/welly#131]
The function `Well.from_las(filename)` causes an exception when using a [pathlib.Path](https://docs.python.org/3/library/pathlib.html#pure-paths) object instead of a string. This is common use case on Windows. I'll provide a PR to fix this later today based on @dcslagel's [earlier fix](https://github.com/kinverarity1/lasio/pull/294) to lasio.

![image](https://user-images.githubusercontent.com/4525931/83955724-6c5f4d80-a895-11ea-8e13-d806ed86edae.png)

**Comment by kwinkunks** [comment]
Thank you Kent!
