### ISSUE TITLE
Measured Depth (ft) converting to Measure Depth (meters)

### ISSUE THREAD

**Issue by NicolasMorton** [agile-geoscience/welly#166]
For some reason when using this package, it displays the md in the tracks as meters rather than ft. Is there a way to avoid this?

**Comment by mtb-za** [comment]
For more recent versions of welly, you should get a FutureWarning when loading a LAS file: `FutureWarning: From v0.5 the default will be 'original', keeping whatever is used in the LAS file. If you want to force conversion to metres, change your code to use "index='m'".`). The current behaviour converts to metres. If you want to change it to feet explicitly, then pass `index='ft` when loading, something like:
```python
from welly import Well

w = Well.from_las('../data/my_las_file.las', index='ft')
```

**Comment by NicolasMorton** [comment]
That did the trick, I should have noticed the index comment. Thank you!

**Comment by mtb-za** [comment]
Happy to have helped. :)

**Comment by kwinkunks** [comment]
This is now fully fixed in `develop`, to be released soon.
