### ISSUE TITLE
Could we load welltops (zone or formation sheet) with welly 0.4 version?

### ISSUE THREAD

**Issue by yummy527** [agile-geoscience/welly#167]
Just knew Welly, and found it useful. Thanks for developing and sharing it.
Finding no tricks about weltop in your tutorial folder, so here to ask: could we load welltops sheet into Welly at present?

**Comment by mtb-za** [comment]
What sort of format are you working with for your welltops? Welly is intended more for working with logs and plotting the curves contained within LAS files. It is possible that you are looking for something like [`Striplog`](https://github.com/agile-geoscience/striplog) instead?

**Comment by EvanBianco** [comment]
Yes, as @mtb-za suggestions you can create you well object in the usual way,

`w = Well.from_las('your_las_file.las')`

And then create an independent `Striplog` containing the tops. For instance,

`from striplog import Striplog`

`tops = Striplog.from_csv('your_tops.csv')`

And then you could attach your `Striplog` to the well like so,

`w.data['tops'] = tops` 

This will enable you to do all sorts of manipulations between the well's data and the tops.
