### ISSUE TITLE
BUG: Memory leaks when read las file

### ISSUE THREAD

**Issue by kerim371** [agile-geoscience/welly#174]
Hi,

I noticed that when I try to read many LAS files in loop the memory leaks is significant.
I use the following code:
```python
from welly import Well
from os import listdir
from os.path import isfile, join


p = r'/some/path'
files = [f for f in listdir(p) if isfile(join(p, f))]

for f in files:
    if f.startswith('.'):
        continue
    w = Well.from_las(p + '/' + f, index='meter')
```
As input data I use [Teapot Dome](https://wiki.seg.org/wiki/Teapot_dome_3D_survey)

I'm not sure whether the leaking module is welly or lasio but I decided to report it here as I use welly.

Welly version: 0.4.10
Python: 3.6.7
Ubuntu 20.04

**Comment by kinverarity1** [comment]
What version of lasio is installed?

**Comment by kerim371** [comment]
@kinverarity1 hi,

lasio version **0.29**

**Comment by kwinkunks** [comment]
Thank you for raising this. How does the memory leak manifest itself? I'm not sure what to look for...

Have you tried projects instead?

```python
from welly import Project
p = Project.from_las('/some/path/*.las')
```

**Comment by kerim371** [comment]
@kwinkunks hi,

Thank you for response.


> Thank you for raising this. How does the memory leak manifest itself? I'm not sure what to look for...


I was trying to read few hundreds of LAS files in loop and I noticed that my app consumes more and more GB of RAM. I could detect this by watching Ubuntu's System Monitor memory consumption. 
I guess to prove or dispute that I think you would need to test the code above on pretty large collection of LAS files. 
Also I use custom python build 3.6.7 (on Ubuntu 20.04), so I think first of all we should understand whether the leakage is caused **welly (lasio)** or my custom python build is the main culprit.



> Have you tried projects instead?

Thank you didn't know that. I will try as soon as possible.

**Comment by kerim371** [comment]
@kwinkunks hi,

I just tried to use `Project`. 

I have 322 las files in the dir and after I execute `p = Project.from_las('/some/path/*.las')` I can see that the memory consumtion growths approximately by 2 Gb. That is fine because the var `p` stores 322 wells (as I understand). But when I delete the `p` the consumed memory stays busy, it is not freed up after I execute `del p`. 

By the way in my special case it is difficult to use `Project` to solve my task as my las files store UWI within API code. Thus welly unable to recognise UWI. But still in general I find `Project` very useful, thank you for the library!

**Comment by kerim371** [comment]
> I think it's normal Python behaviour for objects to remain in memory until they are garbage collected by the interpreter, something one doesn't normally need to interfere with.

I think it is a little weird. For example here is my case:
the app provides GUI to read LAS files using welly library and save the data under different binary format (hdf5). After the data is read/written we don't need welly anymore but the consumed memory is not freed up. That means few Gb of RAM is occupied in waste. The app is written mainly in C++.

I don't have much experience with python but are you sure that this behavior is fine? If so then I should probably search for a way to manually free the consumed memory without relaunching the app...



> It's possible to write a transformer to extract the UWI from the API code during loading, for example see **Coping with messy LAS** at the end of here: https://github.com/agile-geoscience/welly/blob/master/tutorial/06_Welly_and_LAS.ipynb (Or you could deal with it after loading by looping over the wells in `p`.)

Thank for the link, that is pretty interesting although it is always a headache to work with regular expressions for me 😅.
By the way is it possible to create `Project` from selected files only (`["/path1/to/file1.las", "/path2/to/file2.las"]`) and not from the directory?

**Comment by kwinkunks** [comment]
OR, for the memory thing maybe Python needs the explicit signal in your case; I would use `del`.

`Project.from_las()` accepts POSIX-style paths with wildcards OR you can pass in a list (or tuple or whatever) of filenames.

**Comment by kerim371** [comment]
@kwinkunks thank you for reply,

I just tried to explicitly delete items from `Project` but I got error:
```python
from welly import Project
p = Project.from_las('/mypath/*.LAS')
len(p)    # 322
del p[0]
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: __delitem__
```

Also I just tried the following code and it also ended up in consequent memory consumption:
```python
from welly import Well
from os import listdir
from os.path import isfile, join
from os import listdir


p = r'/home/kerim/Documents/ColadaData/Teapot/DataSets/Well Log/CD Files/LAS_log_files/Deeper_LAS_files/'
files = [f for f in listdir(p) if isfile(join(p, f))]

for f in files:
    if f.startswith('.'):
        continue
    w = Well.from_las(p + f, index='meter')
    del w
```

**Comment by kwinkunks** [comment]
Indeed, you cannot delete an item from a project -- I have fixed this in the `develop` branch, it will be in the next release.

It occurs to me that `del` is not guaranteed to actually remove things from memory, only from the namespace. To remove from memory, I think you need to invoke the garbage collector explicitly. See https://docs.python.org/3/library/gc.html

**Comment by kerim371** [comment]
@kinverarity1 it seems that the memory consumtion is invoked by the `lasio`. The code below leads to the same problem:
```python
import lasio
from os import listdir
from os.path import isfile, join
import gc

p = r'/some/path/'
files = [f for f in listdir(p) if isfile(join(p, f))]
for f in files:
    if f.startswith('.'):
        continue
    las = lasio.read(p + f)
    del las
    gc.collect()    # garbage collector doesn't help
```
I can see that the similar error is described [here](https://stackoverflow.com/questions/1316767/how-can-i-explicitly-free-memory-in-python). I feel like there should be a solution or a workaround..

**Comment by kinverarity1** [comment]
I'm not sure what to do to fix it, sorry!

@dcslagel any ideas? Are we keeping references to objects outside LASFile's scope inside LASFile objects that is preventing them being garbage-collected? Maybe something in `lasio.defaults.py`?

**Comment by kinverarity1** [comment]
@kerim371 please feel free to open this issue on the lasio tracker. Clearly not a welly issue.

**Comment by kerim371** [comment]
@kwinkunks my appologize, the memory leak used to be invoked be the application that I use. 
The app writes logs and sets the default [logging](https://docs.python.org/3/library/logging.html) level to `DEBUG`. When reading many las files I get many messages from lasio that the app writes to the file and this invokes memory consumption.
