### ISSUE TITLE
`Project.df()` has index columns out of order

### ISSUE THREAD

**Issue by kwinkunks** [agile-geoscience/welly#183]
Multi-index must be the other way around. As a result, you cannot (say) index by well to get a plot.

![image](https://user-images.githubusercontent.com/1692372/148432323-b229d616-8ab3-4827-a360-3eb508bb1bf9.png)

**Comment by patrick-reinhard** [comment]
I think this can be closed ? @kwinkunks

**Comment by kwinkunks** [comment]
Looks good, thank you Patrick!
