### ISSUE TITLE
Cross-section of welly objects

### ISSUE THREAD

**Issue by EvanBianco** [agile-geoscience/welly#20]
It might be another Class at a higher level than welly. Perhaps more like a Geotransect view, but it should be relatively straightforward to apply a Legend to many welly objects (in a list) and then produce a cross-section.

Options may include: 

- datums for flattening,

-  relative or absolute spacing

- set scale: e.g. (1:250, 1:500, 1:1250, etc)

**Comment by kwinkunks** [comment]
Yes, this is above `welly`'s pay grade.
