### ISSUE TITLE
Select which curves to save to LAS file

### ISSUE THREAD

**Issue by EvanBianco** [agile-geoscience/welly#25]
Would be nice to pass in a list of mnemonics to `Welly.to_las()` to create a new las containing only a subset of all the curves in the well object.

**Comment by EvanBianco** [comment]
welly's save `to_las()' from `lasio.las.write(...)` isn't working. Once the bug is fixed from the dependancy then the enhancement will 'probably' work as expected.

**Comment by kinverarity1** [comment]
I'll have a look at it today

**Comment by kwinkunks** [comment]
I think I fixed this with 832ec2edc91831782f03eaa2ea2e57e6b8bf8ba5 and then the buggy thing with 5ec0208
