### ISSUE TITLE
Make well.plot() take project curve aliases

### ISSUE THREAD

**Issue by EvanBianco** [agile-geoscience/welly#56]
Make a track list for well plotting based on curve aliases so the same track configuration can be passed from one well to the next within a project. Sort of like a template.

**Comment by kwinkunks** [comment]
Done

![image](https://cloud.githubusercontent.com/assets/1692372/17061695/2bb81ff0-5006-11e6-88e9-b8a4b4c58b25.png)

**Comment by kwinkunks** [comment]
PS Also just fixed the small bug hiding the track titles in the above image.
