### ISSUE TITLE
Method to export well as DataFrame, curves as DataSeries?

### ISSUE THREAD

**Issue by EvanBianco** [agile-geoscience/welly#70]
Pandas may not be ideal of most petrophysical curve operations, but it is popular for data exploration, so maybe worth considering a DataFrame that can include some user-defined essential header information.

**Comment by kwinkunks** [comment]
FYI, `Well.las.df()` works as-is (thanks to `lasio`)... but we could send more into the df.

**Comment by kwinkunks** [comment]
Enhancement idea: connect dataframe to welly's data, or make a new, connected dataframe.

**Comment by kwinkunks** [comment]
Implemented for `Well` and `Project`, but not rigorously tested yet. 

You can pass keys (i.e. curve names) at the `Well` level, but not the `Project` level.
