### ISSUE TITLE
well.df() is confusing

### ISSUE THREAD

**Issue by stevejpurves** [agile-geoscience/welly#94]
It seems like `well.df()` returns the `df` associated with the original las file rather than the current well object. This is confusing for example if you have added new derived curves to a well object, and then want to flip the whole thing to a DataFrame then you are missing columns. Wouldn't it be more consistent to have this retrun a df based o the current object?

**Comment by kwinkunks** [comment]
Yes, it definitely would. The original would be available under `w.las.df` anyway. On it!

**Comment by kwinkunks** [comment]
Closing as dupe of #70  - but I'm still fixing it :)
